### ISSUE TITLE
package com.hygenics.scala does not exist

### ISSUE THREAD

**Issue by chlin501** [asevans48/OpenETL#1]
When building source by `mvn clean package`, it throws `package com.hygenics.scala does not exist`.

It seems that some files are missing such as FileOps.
```
OpenETL/hygenicsparser/src/main/java/com/hygenics/parser/Mapper.java:[18,26]
OpenETL/hygenicsparser/src/main/java/com/hygenics/parser/MainApp.java:[13,26]
OpenETL/hygenicsparser/src/main/java/com/hygenics/parser/MainApp.java:[14,26]
OpenETL/hygenicsparser/src/main/java/com/hygenics/parser/CleanFolder.java:[14,26]
OpenETL/hygenicsparser/src/main/java/com/hygenics/parser/ParseDispatcher.java:[29,26]
```

**Comment by asevans48** [comment]
They should not be missing. I see them under /src/main/scala. You may need to modify the POM with netalchim and the scala maven plugin. The Scala IDE has been an enormous pain in terms of this. I have been building this project with eclipse using maven as required by the Scala IDE. In some imports, it has been necessary to literally move the folders back underneath the main project for them to be picked up. I plan on cleaning up this project then deleting the repo after moving things to Goat Herder and making this an SBT project.  The project will be moving to Intellij.
